# Generated by Django 4.0 on 2021-12-11 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('type', models.IntegerField(choices=[(0, 'Normal'), (1, 'Join'), (2, 'Left')], default=0)),
            ],
        ),
    ]
