# Generated by Django 4.0 on 2021-12-12 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='type',
        ),
    ]
